import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogDescription } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { FileText, Send, DollarSign, Calculator } from "lucide-react";
import { format } from "date-fns";

export const BillingManagement = () => {
  const queryClient = useQueryClient();
  const [selectedOrg, setSelectedOrg] = useState<string>("");
  const [invoiceData, setInvoiceData] = useState({
    amount: "",
    dueDate: "",
    notes: ""
  });
  const [isAutoGenerateDialogOpen, setIsAutoGenerateDialogOpen] = useState(false);
  const [selectedOrgForAuto, setSelectedOrgForAuto] = useState("");

  const { data: organizations } = useQuery({
    queryKey: ['billing-organizations'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('organisations')
        .select('id, name')
        .eq('status', 'active');
      
      if (error) throw error;
      return data;
    }
  });

  const { data: invoices } = useQuery({
    queryKey: ['all-invoices'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('invoices')
        .select('*, organisations(name)')
        .order('created_at', { ascending: false });
      
      if (error) throw error;
      return data;
    }
  });

  const { data: billingPreview, isLoading: isLoadingPreview } = useQuery({
    queryKey: ['billing-preview', selectedOrgForAuto],
    enabled: !!selectedOrgForAuto && isAutoGenerateDialogOpen,
    queryFn: async () => {
      const { data, error } = await supabase.rpc('calculate_organization_monthly_bill', {
        org_id: selectedOrgForAuto
      });
      
      if (error) throw error;
      return data as Array<{
        role: string;
        user_count: number;
        price_per_user: number;
        subtotal: number;
        total: number;
      }>;
    }
  });

  const { data: rolePricing } = useQuery({
    queryKey: ['role-pricing'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('role_pricing')
        .select('*');
      
      if (error) throw error;
      return data;
    }
  });

  const generateInvoiceMutation = useMutation({
    mutationFn: async () => {
      const { data: invNumber, error: numberError } = await supabase
        .rpc('generate_invoice_number');

      if (numberError) throw numberError;

      const { error } = await supabase
        .from('invoices')
        .insert({
          organisation_id: selectedOrg,
          invoice_number: invNumber,
          amount: parseFloat(invoiceData.amount),
          due_date: invoiceData.dueDate,
          status: 'draft',
          notes: invoiceData.notes,
          line_items: []
        });

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['all-invoices'] });
      toast.success('Invoice created');
      setInvoiceData({ amount: "", dueDate: "", notes: "" });
      setSelectedOrg("");
    },
    onError: (error) => {
      toast.error('Failed to create invoice: ' + error.message);
    }
  });

  const sendInvoiceMutation = useMutation({
    mutationFn: async (invoiceId: string) => {
      const { error } = await supabase
        .from('invoices')
        .update({ status: 'sent', sent_at: new Date().toISOString() })
        .eq('id', invoiceId);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['all-invoices'] });
      toast.success('Invoice sent to organization');
    }
  });

  const autoGenerateInvoiceMutation = useMutation({
    mutationFn: async () => {
      if (!selectedOrgForAuto || !billingPreview || billingPreview.length === 0) return;

      const total = billingPreview.reduce((sum, item) => sum + (item.subtotal || 0), 0);
      const lineItems = billingPreview.map(item => ({
        role: item.role,
        user_count: item.user_count,
        price_per_user: item.price_per_user,
        subtotal: item.subtotal
      }));

      const nextMonth = new Date();
      nextMonth.setMonth(nextMonth.getMonth() + 1);

      const { data: invNumber, error: numberError } = await supabase
        .rpc('generate_invoice_number');

      if (numberError) throw numberError;

      const { error } = await supabase
        .from('invoices')
        .insert({
          organisation_id: selectedOrgForAuto,
          invoice_number: invNumber,
          amount: total,
          due_date: nextMonth.toISOString().split('T')[0],
          status: 'draft',
          notes: `Auto-generated invoice for ${format(new Date(), 'MMMM yyyy')}`,
          line_items: lineItems
        });

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['all-invoices'] });
      setIsAutoGenerateDialogOpen(false);
      setSelectedOrgForAuto("");
      toast.success('Invoice auto-generated successfully');
    },
    onError: (error) => {
      toast.error('Failed to generate invoice: ' + error.message);
    }
  });

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Role Pricing</CardTitle>
          <CardDescription>Monthly pricing for each user role</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-3 gap-4">
            {rolePricing?.map((pricing: any) => (
              <Card key={pricing.id}>
                <CardContent className="pt-6 text-center">
                  <DollarSign className="w-8 h-8 mx-auto mb-2 text-primary" />
                  <h3 className="font-semibold capitalize">{pricing.role.replace('_', ' ')}</h3>
                  <p className="text-2xl font-bold text-primary">
                    {pricing.price_per_month.toLocaleString()} {pricing.currency}
                  </p>
                  <p className="text-sm text-muted-foreground">per month</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>Invoice Management</CardTitle>
              <CardDescription>Create and send invoices to organizations</CardDescription>
            </div>
            <div className="flex gap-2">
              <Dialog open={isAutoGenerateDialogOpen} onOpenChange={setIsAutoGenerateDialogOpen}>
                <DialogTrigger asChild>
                  <Button variant="outline">
                    <Calculator className="w-4 h-4 mr-2" />
                    Auto-Generate Invoice
                  </Button>
                </DialogTrigger>
                <DialogContent>
                  <DialogHeader>
                    <DialogTitle>Auto-Generate Invoice</DialogTitle>
                    <DialogDescription>Generate invoice based on active users and roles</DialogDescription>
                  </DialogHeader>
                  <div className="space-y-4">
                    <div>
                      <Label>Organization</Label>
                      <Select value={selectedOrgForAuto} onValueChange={setSelectedOrgForAuto}>
                        <SelectTrigger>
                          <SelectValue placeholder="Select organization" />
                        </SelectTrigger>
                        <SelectContent>
                          {organizations?.map((org: any) => (
                            <SelectItem key={org.id} value={org.id}>
                              {org.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>

                    {isLoadingPreview && <div>Calculating...</div>}
                    
                    {billingPreview && billingPreview.length > 0 && (
                      <div className="space-y-3 p-4 bg-muted rounded-lg">
                        <h4 className="font-semibold">Billing Preview</h4>
                        {billingPreview.map((item, idx) => (
                          <div key={idx} className="flex justify-between text-sm">
                            <span className="capitalize">{item.role.replace('_', ' ')}: {item.user_count} × {item.price_per_user.toLocaleString()} TZS</span>
                            <span className="font-medium">{item.subtotal.toLocaleString()} TZS</span>
                          </div>
                        ))}
                        <div className="flex justify-between pt-2 border-t font-bold">
                          <span>Total Monthly</span>
                          <span>{(billingPreview.reduce((s, i) => s + (i.subtotal || 0), 0)).toLocaleString()} TZS</span>
                        </div>
                      </div>
                    )}

                    <Button 
                      onClick={() => autoGenerateInvoiceMutation.mutate()}
                      disabled={!selectedOrgForAuto || !billingPreview || autoGenerateInvoiceMutation.isPending}
                      className="w-full"
                    >
                      Generate Invoice
                    </Button>
                  </div>
                </DialogContent>
              </Dialog>

              <Dialog>
                <DialogTrigger asChild>
                  <Button>
                    <FileText className="w-4 h-4 mr-2" />
                    Create Invoice
                  </Button>
                </DialogTrigger>
                <DialogContent>
                  <DialogHeader>
                    <DialogTitle>Create New Invoice</DialogTitle>
                    <DialogDescription>Fill in the details to create and save a draft invoice.</DialogDescription>
                  </DialogHeader>
                  <div className="space-y-4">
                    <div>
                      <Label>Organization</Label>
                      <Select value={selectedOrg} onValueChange={setSelectedOrg}>
                        <SelectTrigger>
                          <SelectValue placeholder="Select organization" />
                        </SelectTrigger>
                        <SelectContent>
                          {organizations?.map((org: any) => (
                            <SelectItem key={org.id} value={org.id}>
                              {org.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                    <div>
                      <Label>Amount (TZS)</Label>
                      <Input
                        type="number"
                        value={invoiceData.amount}
                        onChange={(e) => setInvoiceData({ ...invoiceData, amount: e.target.value })}
                        placeholder="50000"
                      />
                    </div>
                    <div>
                      <Label>Due Date</Label>
                      <Input
                        type="date"
                        value={invoiceData.dueDate}
                        onChange={(e) => setInvoiceData({ ...invoiceData, dueDate: e.target.value })}
                      />
                    </div>
                    <div>
                      <Label>Notes</Label>
                      <Input
                        value={invoiceData.notes}
                        onChange={(e) => setInvoiceData({ ...invoiceData, notes: e.target.value })}
                        placeholder="Optional notes"
                      />
                    </div>
                    <Button 
                      onClick={() => generateInvoiceMutation.mutate()} 
                      disabled={!selectedOrg || !invoiceData.amount || !invoiceData.dueDate || generateInvoiceMutation.isPending}
                      className="w-full"
                    >
                      Generate Invoice
                    </Button>
                  </div>
                </DialogContent>
              </Dialog>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <h3 className="text-sm font-medium text-muted-foreground">Draft Invoices</h3>
            {invoices?.filter((inv: any) => inv.status === 'draft').map((invoice: any) => (
              <Card key={invoice.id} className="border-2">
                <CardContent className="pt-6">
                  <div className="flex items-center justify-between mb-4">
                    <div>
                      <h3 className="font-semibold">{invoice.invoice_number}</h3>
                      <p className="text-sm text-muted-foreground">{invoice.organisations?.name}</p>
                    </div>
                    <Badge variant="secondary">{invoice.status}</Badge>
                  </div>
                  <div className="grid grid-cols-3 gap-4 text-sm mb-4">
                    <div>
                      <p className="text-muted-foreground">Amount</p>
                      <p className="font-semibold">{invoice.amount.toLocaleString()} {invoice.currency}</p>
                    </div>
                    <div>
                      <p className="text-muted-foreground">Due Date</p>
                      <p className="font-semibold">{new Date(invoice.due_date).toLocaleDateString()}</p>
                    </div>
                    <div>
                      <p className="text-muted-foreground">Created</p>
                      <p className="font-semibold">{new Date(invoice.created_at).toLocaleDateString()}</p>
                    </div>
                  </div>
                  <Button
                    onClick={() => sendInvoiceMutation.mutate(invoice.id)}
                    size="sm"
                    className="w-full"
                  >
                    <Send className="w-4 h-4 mr-2" />
                    Send to Organization
                  </Button>
                </CardContent>
              </Card>
            ))}
            {invoices?.filter((inv: any) => inv.status === 'draft').length === 0 && (
              <p className="text-sm text-muted-foreground">No draft invoices</p>
            )}
          </div>

          <div className="space-y-2 mt-6">
            <h3 className="text-sm font-medium text-muted-foreground">Sent Invoices</h3>
            {invoices?.filter((inv: any) => inv.status === 'sent' || inv.status === 'overdue').map((invoice: any) => (
              <Card key={invoice.id} className="border-2">
                <CardContent className="pt-6">
                  <div className="flex items-center justify-between mb-4">
                    <div>
                      <h3 className="font-semibold">{invoice.invoice_number}</h3>
                      <p className="text-sm text-muted-foreground">{invoice.organisations?.name}</p>
                    </div>
                    <Badge variant={invoice.status === 'overdue' ? 'destructive' : 'outline'}>
                      {invoice.status}
                    </Badge>
                  </div>
                  <div className="grid grid-cols-4 gap-4 text-sm">
                    <div>
                      <p className="text-muted-foreground">Amount</p>
                      <p className="font-semibold">{invoice.amount.toLocaleString()} {invoice.currency}</p>
                    </div>
                    <div>
                      <p className="text-muted-foreground">Due Date</p>
                      <p className="font-semibold">{new Date(invoice.due_date).toLocaleDateString()}</p>
                    </div>
                    <div>
                      <p className="text-muted-foreground">Sent Date</p>
                      <p className="font-semibold">{invoice.sent_at ? new Date(invoice.sent_at).toLocaleDateString() : '-'}</p>
                    </div>
                    <div>
                      <p className="text-muted-foreground">Created</p>
                      <p className="font-semibold">{new Date(invoice.created_at).toLocaleDateString()}</p>
                    </div>
                  </div>
                  {invoice.line_items && invoice.line_items.length > 0 && (
                    <div className="mt-4 p-3 bg-muted rounded-lg">
                      <p className="text-xs font-medium mb-2">Line Items</p>
                      {invoice.line_items.map((item: any, idx: number) => (
                        <div key={idx} className="flex justify-between text-xs py-1">
                          <span className="capitalize">{item.role?.replace('_', ' ')}: {item.user_count} × {item.price_per_user?.toLocaleString()} {invoice.currency}</span>
                          <span className="font-medium">{item.subtotal?.toLocaleString()} {invoice.currency}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </CardContent>
              </Card>
            ))}
            {invoices?.filter((inv: any) => inv.status === 'sent' || inv.status === 'overdue').length === 0 && (
              <p className="text-sm text-muted-foreground">No sent invoices</p>
            )}
          </div>

          <div className="space-y-2 mt-6">
            <h3 className="text-sm font-medium text-muted-foreground">Paid Invoices</h3>
            {invoices?.filter((inv: any) => inv.status === 'paid').map((invoice: any) => (
              <Card key={invoice.id} className="border-2 border-green-200">
                <CardContent className="pt-6">
                  <div className="flex items-center justify-between mb-4">
                    <div>
                      <h3 className="font-semibold">{invoice.invoice_number}</h3>
                      <p className="text-sm text-muted-foreground">{invoice.organisations?.name}</p>
                    </div>
                    <Badge variant="default">{invoice.status}</Badge>
                  </div>
                  <div className="grid grid-cols-4 gap-4 text-sm">
                    <div>
                      <p className="text-muted-foreground">Amount</p>
                      <p className="font-semibold">{invoice.amount.toLocaleString()} {invoice.currency}</p>
                    </div>
                    <div>
                      <p className="text-muted-foreground">Due Date</p>
                      <p className="font-semibold">{new Date(invoice.due_date).toLocaleDateString()}</p>
                    </div>
                    <div>
                      <p className="text-muted-foreground">Paid Date</p>
                      <p className="font-semibold">{invoice.paid_date ? new Date(invoice.paid_date).toLocaleDateString() : '-'}</p>
                    </div>
                    <div>
                      <p className="text-muted-foreground">Created</p>
                      <p className="font-semibold">{new Date(invoice.created_at).toLocaleDateString()}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
            {invoices?.filter((inv: any) => inv.status === 'paid').length === 0 && (
              <p className="text-sm text-muted-foreground">No paid invoices</p>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  );
};
