// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shqclgwsgmlnimcggxch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNocWNsZ3dzZ21sbmltY2dneGNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4MzEzNzAsImV4cCI6MjA3NTQwNzM3MH0.Vbn4EEwVPHqVcu3t6H-LYfaO_SWMD0KjLqWzr0izMlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});